### ISSUE TITLE
[Question] Spring Boot metrics with Prometheus and Grafana

### ISSUE THREAD

**Issue by SimonScholz** [Vikaspogu/vikaspogu.github.io#1]
Hi,

thanks for sharing your knowledge on "Spring Boot metrics with Prometheus and Grafana in OpenShift" in your blog post -> https://vikaspogu.dev/posts/springboot-metrics-grafana/

At the very end of your helpful blog post you do have the following screenshot of a really nice Grafana dashboard.

![image](https://user-images.githubusercontent.com/7559962/94665931-0f3c4b80-030d-11eb-8957-baed7205ee38.png)

Could you please share this Grafana dashboard with us? I`d love to include it in our Grafana setup.

Sorry for asking you this via an issue, but your blog does not give any alternative options to reach out for you. ;-)

Thanks a lot in advance. :-)

**Comment by Vikaspogu** [comment]
You can find a lot of dashboards on micrometer [from grafana](https://grafana.com/grafana/dashboards/4701). You can find the dashboard from my blog in this [template](https://gist.githubusercontent.com/Vikaspogu/4a67495acf8dba5dc94837e031129fde/raw/e88f42515c6ed101c9554c7c2425794e80e10a64/openshift-grafana.yaml). Dashboard is created as a configmap named "spring-boot-metrics-dashboard.json"

**Comment by SimonScholz** [comment]
Thank you so much :-)
